version: "3"

services:
  app:
    container_name: keychain-client
    build: .
    restart: always
    env_file: .env
    ports:
      - "${APP_PORT}:80"
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
      - VUE_APP_API_CLIENT_ID=${VUE_APP_API_CLIENT_ID}
      - VUE_APP_API_CLIENT_SECRET=${VUE_APP_API_CLIENT_SECRET}
